/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.uv.sysgen.GUI;

import java.awt.Component;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import mx.uv.sysgen.Logica.Configuración;

/**
 *
 * @author Luis Enrique
 */
public class Ventana_Configuración extends javax.swing.JFrame {
JFileChooser manejadorArchivo;
Configuración conf;

    /**
     * Creates new form Ventana_Confiuración
     */
    public Ventana_Configuración() {
        initComponents();
    }
    
    public void rellenaCampos(){
        this.TFusuario.setText(conf.getUsuario());
        this.TFcontraseña.setText(conf.getContraseña());
        this.TFesquema.setText(conf.getEsquema());
        this.TFrutaReportes.setText(conf.getRuta_Reportes());
        this.CMBmanejador.setSelectedIndex(conf.getManejador()-1);
    }
    
    
    public void GuardarConfiguración(){
        int man=0;
        if (this.CMBmanejador.getSelectedItem().toString().equals("MySQL"))
            man=1;
        else if (this.CMBmanejador.getSelectedItem().toString().equals("Oracle"))
            man=2;
        else
            man=3;
        Configuración nueva=new Configuración();        
          nueva.actualizar(this.TFusuario.getText(),this.TFcontraseña.getText(),this.TFesquema.getText(),man,this.TFrutaReportes.getText());          
          conf.guardarArchivo(nueva);
}
    public void AbrirConfiguración(){
        conf=conf.abrirArchivo();
        rellenaCampos();
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLletrero_grande = new javax.swing.JLabel();
        BTNguardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LBLletreto_BaseDeDatos = new javax.swing.JLabel();
        LBLusuario = new javax.swing.JLabel();
        LBLcontraseña = new javax.swing.JLabel();
        LBLesquema = new javax.swing.JLabel();
        LBLmanejador = new javax.swing.JLabel();
        CMBmanejador = new javax.swing.JComboBox();
        TFesquema = new javax.swing.JTextField();
        TFusuario = new javax.swing.JTextField();
        TFcontraseña = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        LBLletrero_rutaReportes = new javax.swing.JLabel();
        TFrutaReportes = new javax.swing.JTextField();
        BTNbuscar_carpeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones de Configuración");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        LBLletrero_grande.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        LBLletrero_grande.setText("Configuración de SYSGEN");

        BTNguardar.setText("Guardar Configuración");
        BTNguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarActionPerformed(evt);
            }
        });

        LBLletreto_BaseDeDatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLletreto_BaseDeDatos.setText("Base de Datos");

        LBLusuario.setText("Usuario");

        LBLcontraseña.setText("Contraseña");

        LBLesquema.setText("Esquema/Base de datos");

        LBLmanejador.setText("Manejador");

        TFcontraseña.setText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LBLletreto_BaseDeDatos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLesquema)
                                    .addComponent(LBLmanejador))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFesquema, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CMBmanejador, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLusuario)
                                    .addComponent(LBLcontraseña))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFusuario)
                                    .addComponent(TFcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLletreto_BaseDeDatos)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLusuario)
                    .addComponent(TFusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLcontraseña)
                    .addComponent(TFcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLesquema)
                    .addComponent(TFesquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLmanejador)
                    .addComponent(CMBmanejador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LBLletrero_rutaReportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLletrero_rutaReportes.setText("Ruta Absoluta de Reportes");

        BTNbuscar_carpeta.setText("Buscar Carpeta");
        BTNbuscar_carpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscar_carpetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLletrero_rutaReportes)
                    .addComponent(BTNbuscar_carpeta)
                    .addComponent(TFrutaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LBLletrero_rutaReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFrutaReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNbuscar_carpeta)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LBLletrero_grande, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(BTNguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLletrero_grande, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarActionPerformed
        GuardarConfiguración();
        JOptionPane.showMessageDialog(null, "GUARDADO", "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_BTNguardarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       this.CMBmanejador.addItem("MySQL");
       this.CMBmanejador.addItem("Oracle");
       this.CMBmanejador.addItem("Otro");
       conf=new Configuración();
       try{
          AbrirConfiguración();
       }catch(Exception e){
           //significa que es la primera vez que se accede a configuraciones y 
           //aún no existe este archivo
           GuardarConfiguración();
       }
    }//GEN-LAST:event_formComponentShown

    private void BTNbuscar_carpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscar_carpetaActionPerformed
        JFileChooser manejadorArchivo= new JFileChooser();
        if( manejadorArchivo == null ) manejadorArchivo = new JFileChooser();
           manejadorArchivo.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY);
        int seleccion = manejadorArchivo.showSaveDialog(BTNbuscar_carpeta);   
        String ruta="";
        if( seleccion == JFileChooser.APPROVE_OPTION ){
           ruta = manejadorArchivo.getSelectedFile().getAbsolutePath();    
           this.TFrutaReportes.setText(ruta);
        }
    }//GEN-LAST:event_BTNbuscar_carpetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Configuración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Configuración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Configuración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Configuración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Configuración().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNbuscar_carpeta;
    private javax.swing.JButton BTNguardar;
    public javax.swing.JComboBox CMBmanejador;
    private javax.swing.JLabel LBLcontraseña;
    private javax.swing.JLabel LBLesquema;
    private javax.swing.JLabel LBLletrero_grande;
    private javax.swing.JLabel LBLletrero_rutaReportes;
    private javax.swing.JLabel LBLletreto_BaseDeDatos;
    private javax.swing.JLabel LBLmanejador;
    private javax.swing.JLabel LBLusuario;
    public javax.swing.JPasswordField TFcontraseña;
    public javax.swing.JTextField TFesquema;
    public javax.swing.JTextField TFrutaReportes;
    public javax.swing.JTextField TFusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
