/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */ 
package mx.uv.sysgen.BD;


import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Enrique
 */
public class FConsultas1 extends javax.swing.JFrame {
    ResultSet resultados;
    String u;
    String c;
    String e;
    int m;
    String tabla;
    LinkedList<String> letreros=new LinkedList<String>();
    LinkedList<JTextField> campos=new LinkedList<JTextField>();
  



    
    
    /**
     * Creates new form FConsultas
     * 
     */
    public FConsultas1() {
        initComponents();
        final FconfBDtemporal conf=new FconfBDtemporal();
        conf.configurar.addActionListener(new ActionListener(){        
            public void actionPerformed(ActionEvent ex) {
                       c=conf.TFcontraseña.getText();
                       u=conf.TFusuario.getText();
                       e=conf. TFesquema.getText();
                       String man=(String) conf.JCBmanej.getSelectedItem();
                       if (man.equals("MySQL"))   
                           m=1;
                       else if (man.equals("Oracle"))   
                           m=2;
                       else
                           m=3;
                       //mostrar qué manejador se está usando, en la ventana
                       LBLmanejador.setText("Manejador: "+m);
                       LBLmanejador2.setText("Manejador: "+m);
                       conf.dispose();
                     }
        });
        
        conf.setVisible(true);
        conf.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        LBLmanejador = new javax.swing.JLabel();
        BTNbuscarSQL = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JCBtabla = new javax.swing.JComboBox();
        LBLmanejador2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PNcampos = new javax.swing.JPanel();
        BTNbuscarAPY = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable2 = new javax.swing.JTable();
        BTNxml2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTable.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane1.setViewportView(JTable);

        jLabel1.setText("Consulta");

        jTextField1.setToolTipText("Escriba la consulta que será realizada por el manejador de base de datos preseleccionado");
        jTextField1.setName("TFconsulta"); // NOI18N

        LBLmanejador.setText("Manejador: ");
        LBLmanejador.setName("LBLmanejador"); // NOI18N

        BTNbuscarSQL.setText("Buscar");
        BTNbuscarSQL.setName("BTNbuscar"); // NOI18N
        BTNbuscarSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarSQLActionPerformed(evt);
            }
        });

        jButton2.setText("XML");
        jButton2.setName("BTNxml"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNbuscarSQL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LBLmanejador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNbuscarSQL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLmanejador))
        );

        jTabbedPane1.addTab("Consulta SQL", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        JCBtabla.setModel(new javax.swing.DefaultComboBoxModel());
        JCBtabla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCBtablaItemStateChanged(evt);
            }
        });
        JCBtabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBtablaActionPerformed(evt);
            }
        });

        LBLmanejador2.setText("Manejador: ");
        LBLmanejador2.setName("LBLmanejador"); // NOI18N

        jLabel4.setText("Tabla");

        PNcampos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PNcamposLayout = new javax.swing.GroupLayout(PNcampos);
        PNcampos.setLayout(PNcamposLayout);
        PNcamposLayout.setHorizontalGroup(
            PNcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        PNcamposLayout.setVerticalGroup(
            PNcamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BTNbuscarAPY.setText("Buscar");
        BTNbuscarAPY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbuscarAPYActionPerformed(evt);
            }
        });

        JTable2.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane2.setViewportView(JTable2);

        BTNxml2.setText("XML");
        BTNxml2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNxml2ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 373, Short.MAX_VALUE)
                .addComponent(LBLmanejador2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PNcampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(JCBtabla, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(BTNbuscarAPY))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)
                        .addComponent(BTNxml2)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCBtabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNbuscarAPY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLmanejador2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(PNcampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNxml2)
                                    .addComponent(jLabel4))))
                        .addGap(32, 32, 32))))
        );

        jTabbedPane1.addTab("Consulta Apoyada", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt evento de clic en el botón XML
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (resultados!=null){
            ResultSetToXML xml=new ResultSetToXML();
            try{
                xml.crearXML(resultados);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BTNbuscarSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarSQLActionPerformed
        BD base=new BD();
        base.configuraBD(u,c,e,m);
        ResultSet rs = base.consulta(this.jTextField1.getText());

        if (rs!=null){
            resultados= base.consulta(this.jTextField1.getText());    
            DefaultTableModel modelo = new DefaultTableModel();
            modelo=base.consultaAmodelo(this.jTextField1.getText());
            this.JTable.setModel(modelo);
        }
    }//GEN-LAST:event_BTNbuscarSQLActionPerformed
    /**
     * 
     * @param evt evento mostrado de jPanel2
     */
    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
       recargaTablas();
    }//GEN-LAST:event_jPanel2ComponentShown

    /**
     * 
     * @param evt  evento acción en el JCBtabla
     */
    private void JCBtablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBtablaActionPerformed
        //recargaTablas();
     if (JCBtabla.getItemCount()>0){   
        String tab=(String) JCBtabla.getSelectedItem();
        System.out.println(tab);
        tabla=tab;
        letreros=new LinkedList <String>();
        campos=new LinkedList <JTextField>();
        BD base=new BD();
        base.configuraBD(u,c,e,m);
        try {
            letreros=base.getCampos(tab);
        } catch (SQLException ex) {
            Logger.getLogger(FConsultas1.class.getName()).log(Level.SEVERE, null, ex);
        }
        PNcampos.removeAll();
        for (int i=0;i<letreros.size();i++){
            this.PNcampos.add(new JLabel(letreros.get(i))); 
            campos.add(new JTextField());
            this.PNcampos.add(campos.get(i));
        }
        PNcampos.setLayout(new GridLayout(campos.size(), 2, 0, 0));
        PNcampos.updateUI();    
     }
        //new JLabel(campos.get(i);
    }//GEN-LAST:event_JCBtablaActionPerformed

    /**
     * 
     * @param evt clic en el botón buscar de consulta apoyada
     */
    private void BTNbuscarAPYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbuscarAPYActionPerformed
        String cons="select * from "+tabla;
        boolean ban=false;
        boolean esCadena=false;
        int cont=0;
        String extra=" where ";
        for (int i=0;i<letreros.size();i++){
           if (!campos.get(i).getText().isEmpty()){
               ban=true;  
               if (ban==true && cont>0){
                   extra=extra+" and ";
                   }
               //esto es para revisar si el campo es númerico o no
               //si sí unas '' lo envolveran
               
               extra=extra + letreros.get(i)+"=";
               try{
               int prueba=0;
               prueba=Integer.parseInt(campos.get(i).getText());
               }
               catch(Exception e){
                   esCadena=true;
               }
               if (esCadena)
                   extra=extra+"\'"+campos.get(i).getText()+"\'";
               else
               extra=extra+campos.get(i).getText();
               cont=cont+1;
               esCadena=false;
           }
        }
        if (ban!=false)
            cons=cons+extra;
        System.out.println(cons);
        //-------------------------------------------------------------------
        DefaultTableModel modelo = new DefaultTableModel();
        BD base=new BD();
        base.configuraBD(u,c,e,m);
        ResultSet rs = base.consulta(cons);

        if (rs!=null){
            resultados= base.consulta(cons);
            modelo=base.consultaAmodelo(cons);
            this.JTable2.setModel(modelo);
        }
        
    }//GEN-LAST:event_BTNbuscarAPYActionPerformed

    /*
     * clic en el boton xml de consulta apoyada
     */
    private void BTNxml2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNxml2ActionPerformed
        // TODO add your handling code here:
        if (resultados!=null){
            ResultSetToXML xml=new ResultSetToXML();
            try{
                xml.crearXML(resultados);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_BTNxml2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BD base=new BD();
        base.configuraBD(u,c,e,m);
        LinkedList<CampoSQL> a=new LinkedList<CampoSQL>();
        a.add(new CampoSQL("id","varchar(25)",true,false));
        a.add(new CampoSQL("tres","varchar(25)",false,false));
        a.add(new CampoSQL("three","varchar(25)",false,true));
        a.add(new CampoSQL("trois","varchar(25)",false,false));
        base.crearTabla("tres", a);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JCBtablaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCBtablaItemStateChanged
       
    }//GEN-LAST:event_JCBtablaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FConsultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FConsultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FConsultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FConsultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FConsultas1().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNbuscarAPY;
    private javax.swing.JButton BTNbuscarSQL;
    private javax.swing.JButton BTNxml2;
    private javax.swing.JComboBox JCBtabla;
    private javax.swing.JTable JTable;
    private javax.swing.JTable JTable2;
    private javax.swing.JLabel LBLmanejador;
    private javax.swing.JLabel LBLmanejador2;
    private javax.swing.JPanel PNcampos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void recargaTablas() {
        JCBtabla.removeAllItems();
        BD base=new BD();
       base.configuraBD(u,c,e,m);
        LinkedList<String> a;
        try {
            a = base.getTablas();
            for (int i=0;i<a.size();i++)
             JCBtabla.addItem(a.get(i));
                
        } catch (SQLException ex) {
            Logger.getLogger(FConsultas1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
